### ISSUE TITLE
Main Pollutant missing 

### ISSUE THREAD

**Issue by johntdyer** [dnguyen800/air-visual-card#1]
Appears that AirVisual has changed their API and no longer has main pollutant in their free plan. This is being discussed in this thread.

https://community.home-assistant.io/t/air-visual-main-pollutant-v-0-95-4/124080

It appears an update is required to remove this or perhaps switch to another provider.  I have noticed a few others that appear to still support this

https://breezometer.com/products/air-quality-api
https://docs.airnowapi.org/login?index=

 I am sure there are others as well

**Comment by dnguyen800** [comment]
I updated the code so that the card doesn't crash when one of the sensors isn't present. Feel free to test and let me know.
