### ISSUE TITLE
readme suggestion for example for icons folder path

### ISSUE THREAD

**Issue by marecabo** [dnguyen800/air-visual-card#10]
When installing the card with HACS, the following value for the `icons` option makes use of the already downloaded icons in the `config\www\community\air-visual-card` folder.

```yaml
icons: "/community_plugin/air-visual-card"
```

**Comment by dnguyen800** [comment]
Thanks for the advice, I'll update the readme with that example when I have a moment.

**Comment by dnguyen800** [comment]
added

**Comment by marecabo** [comment]
HACS changed their paths for plugins ([doc](https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles)). It now can either be
```yaml
icons: "/hacsfiles/air-visual-card"
```
or
```yaml
icons: "/local/community/air-visual-card"
```
where the former is recommended by HACS.

**Comment by dnguyen800** [comment]
updated, thanks.
