### ISSUE TITLE
Sensor's names are different

### ISSUE THREAD

**Issue by pherbel** [dnguyen800/air-visual-card#13]
With my setup: latest 0.104.0 HA
The sensors name were different like this
**sensor.us_air_pollution_level -> sensor.u_s_air_pollution_level**

Proper config.
> - type: custom:air-visual-card
>     air_pollution_level: sensor.u_s_air_pollution_level
>     air_quality_index: sensor.u_s_air_quality_index
>     main_pollutant: sensor.u_s_main_pollutant
>     temp: weather.dark_sky
>     city: 'Budapest'

**Comment by dnguyen800** [comment]
unfortunately that is an issue with the sensor, not the card.

**Comment by pherbel** [comment]
I know it is not card issue. I just inform you about it. Maybe it can be just fixed in the doc.
