### ISSUE TITLE
I got this error..  Doesn't look like it's actually line 164 or 63 that's a culprit.

### ISSUE THREAD

**Issue by rezanaima** [dnguyen800/air-visual-card#14]
Mon Jan 20 2020 19:26:02 GMT-0800 (Pacific Standard Time)
http://10.0.0.126:8123/local/air-visual-card.js:164:63 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by dnguyen800** [comment]
I released a new version with better error handling--can you check if this issue still exists?
