### ISSUE TITLE
Rounded CSS Style

### ISSUE THREAD

**Issue by octaviz** [dnguyen800/air-visual-card#18]
Do you know if you can round the corners in any way ?, I am trying to apply the CSS but it does not work, I have almost all the cards with the rounded corner

![Screenshot_1](https://user-images.githubusercontent.com/856579/75695330-3153e980-5caa-11ea-975a-494540ce216c.png)

Thanks you!!

**Comment by dnguyen800** [comment]
Unfortunately I don't know how to load the default CSS style applied to Lovelace cards, I hardcode them in the .js file. How are you applying CSS styles to these other cards? 

In the meantime, I'll add an option where you can add in your CSS style into the card. Will update on the weekend.

If you want to play around with the CSS, you can edit the .js file directly and edit the CSS section. Should be easy to spot.

**Comment by octaviz** [comment]
As soon as I can try to modify the CSS of the .js file to see if I can change it, I will tell you if it works.

Example CSS in Card

```
style: |
  ha-card {
    border: solid 1px #ffc500;
    
    border-radius: 10px;
    background: rgb(255,70,70);
          background: linear-gradient(349deg, rgba(0,51,102,1) 24%, rgba(0,80,255,1) 100%);
          color: white;
          }
          ha-icon {
          color: white;
  }
```

Thanks!!

**Comment by dnguyen800** [comment]
Unfortunately I tried modifying the CSS in the .js file but didn't have any luck adding the border-radius, so I don't have any solution or workaround at the moment.

**Comment by scstraus** [comment]
I just went in and changed border-radius in my theme definition itself and it applied to every card except this one.

**Comment by Ndrinta** [comment]
Have someone found a solution? I'm really interested in this "feature".

**Comment by Swampen** [comment]
I have made a pull request that should fix this issue 😊

**Comment by dnguyen800** [comment]
Merged the PR, thanks @Swampen !
