### ISSUE TITLE
Error "can’t define property “icons”: Object is not extensible" on .106.5

### ISSUE THREAD

**Issue by scstraus** [dnguyen800/air-visual-card#19]
I’m getting the following on .106.5:

can’t define property “icons”: Object is not extensible

![image](https://user-images.githubusercontent.com/7644023/76153109-b898c700-60c7-11ea-96e4-26c24bbff2bb.png)

**Comment by dnguyen800** [comment]
Are you using the latest version of the card and did you wipe the browser cache? Another person had the same problem but forgot to wipe the cache.

**Comment by riqjuan** [comment]
Also seeing this, although mine has slightly different wording
![image](https://user-images.githubusercontent.com/51686796/76182954-d88ccf80-621a-11ea-8aba-f44c22e6e6f2.png)

Clearing browser cache/data has no effect -- also on 0.106.5

**Comment by scstraus** [comment]
> Are you using the latest version of the card and did you wipe the browser cache? Another person had the same problem but forgot to wipe the cache.

I believe yes on both counts unless you have updated it in the last month.

**Comment by dnguyen800** [comment]
I released a new version of the card that now shows the version info when you look at the browser console. If the version is not showing, then you're not running v0.0.11

To access the console on Google Chrome:

Right click anywhere on Home Assistant UI >> Inspect >> Console.

Make sure cache is cleared. There is a setting you can enable in Developer Tools to always disable cache when Inspect mode is on.

**Comment by riqjuan** [comment]
v0.0.11 has resolved my issue, card is now working correctly - thanks @dnguyen800

**Comment by scstraus** [comment]
Yep, my problem too. Sorry for the bother. Should have checked that I was running the latest stuff better.
