### ISSUE TITLE
Error "attemped to assign to readonly property"after updated 0.106.5

### ISSUE THREAD

**Issue by noelesther** [dnguyen800/air-visual-card#20]
I got error on 0.106.5

attemped to assign to readonly property

Thanks. 
<img width="565" alt="스크린샷 2020-03-09 오후 1 48 35" src="https://user-images.githubusercontent.com/25280660/76189221-b5f3ba00-620c-11ea-9c0e-3f728a62f362.png">

**Comment by Ndrinta** [comment]
Looks like your entities naming isn't consistent, maybe you meant that but maybe it's a mistake. Can you double check that?

**Comment by noelesther** [comment]
> Looks like your entities naming isn't consistent, maybe you meant that but maybe it's a mistake. Can you double check that?

Before update No error. but, after update 0.106.5 has error. not change anything of setting. Is it a mistake of setting?

**Comment by Ndrinta** [comment]
I would try to reinstall the airvisual card add on.
maybe double check also that the sensor are properly working and that in the lovelace raw you actually have the "header" too
`- type: js
    url: /community_plugin/air-visual-card/air-visual-card.js`

**Comment by noelesther** [comment]
> I would try to reinstall the airvisual card add on.
> maybe double check also that the sensor are properly working and that in the lovelace raw you actually have the "header" too
> `- type: js url: /community_plugin/air-visual-card/air-visual-card.js`

when reinstall and add ?v=1.0.0 work fine. thanks.
