### ISSUE TITLE
After update to 0.107.1 air visual is not working

### ISSUE THREAD

**Issue by daha76** [dnguyen800/air-visual-card#26]
Hello,

for some reason this card can't get data after I updated to 0.107.1. When I reverted back to 0.106.6 all is ok and works normally. Seems like 0.107.1 is quite buggy, because some other integrations also stopped working properly, like denonavr, asuswrt, Mibox, and maybe some others.

**Comment by DMQ8** [comment]
Confirmed, same here on Hassio.

**Comment by arek156** [comment]
Hello
I have a problem with the air visual card plugin. I have the HA 0.107.4 version, I have added air visual card in the integration and the API key in config.yaml.
When I add a plugin on the main screen I have this error:
![visualcard](https://user-images.githubusercontent.com/39795733/77233057-3fa86d80-6ba5-11ea-8af5-a611b72d709c.JPG)

**Comment by DMQ8** [comment]
> Hello
> I have a problem with the air visual card plugin. I have the HA 0.107.4 version, I have added air visual card in the integration and the API key in config.yaml.
> When I add a plugin on the main screen I have this error:
> ![visualcard](https://user-images.githubusercontent.com/39795733/77233057-3fa86d80-6ba5-11ea-8af5-a611b72d709c.JPG)

Setting using configuration.yaml didn't work for me as in previous version 0.106.x although I followed the new setup guide for 107.x, doing the setup in the user interface and Inserting the API key directly using the integrations user interface worked for me as the steps I mentioned. 

Make sure the sensors name are correct in your case and it has values Developer-tools>States, The following is card setting:
`air_pollution_level: sensor.u_s_air_pollution_level
air_quality_index: sensor.u_s_air_quality_index
city: Your City Name
icons: 'https://cdn.jsdelivr.net/gh/dnguyen800/air-visual-card@0.0.4/dist'
main_pollutant: sensor.u_s_main_pollutant
type: 'custom:air-visual-card'`

**Comment by arek156** [comment]
Reinstalled the add-on without any changes, all sensors are added correctly. I am only thinking about the message that coustom element not found. The add-on is installed in HACS, it is also integrated and reporting data correctly.

**Comment by daha76** [comment]
I deleted all air visual integrations and entities, added only this in configuration.yalm:

airvisual:
    api_key: YOUR_AIRVISUAL_API_KEY

restarted server and added air visual card again and all works as before.

**Comment by arek156** [comment]
@daha76 can you show your air visual card script as it looks on the lovelace card?

**Comment by daha76** [comment]
air_pollution_level: sensor.u_s_air_pollution_level
air_quality_index: sensor.u_s_air_quality_index
city: Kosice
country: Slovakia
icons: 'https://cdn.jsdelivr.net/gh/dnguyen800/air-visual-card@0.0.4/dist'
main_pollutant: u_s_main_pollutant
temp: weather.domov
type: 'custom:air-visual-card'

**Comment by arek156** [comment]
unfortunately it doesn't work for me, I have the message:
Error: Custom element not found: air-visual-card

**Comment by daha76** [comment]
Seem like you have to reinstall air-visual-card

**Comment by arek156** [comment]
problem solved, i had not updated HACS. Everything works.
