### ISSUE TITLE
Flickering Face image

### ISSUE THREAD

**Issue by Mariusthvdb** [dnguyen800/air-visual-card#29]
![May-13-2020 09-35-30](https://user-images.githubusercontent.com/33354141/81785596-c53dff00-94fe-11ea-9ed2-8ad741942b40.gif)

as posted [here](https://community.home-assistant.io/t/airvisual-lovelace-card-for-air-quality-index/80348/56?u=mariusthvdb), I seek some assistance...

thanks if you can have a look, I don't have any error logs  I am afraid, so not much to go on really, other than my HA Hassio being on 109.6

**Comment by Mariusthvdb** [comment]
HI, meanwhile we're o HA 0.111.3 and the face keeps flickering.

Could this be caused by settings in the face class? does the face img {} do anything at all?

maybe width and height should both be set for the img?

**Comment by Swampen** [comment]
I can try to take a look at this if you still have the issue?

**Comment by Mariusthvdb** [comment]
yes please! its not always there, but have a look now:

![airvisual](https://user-images.githubusercontent.com/33354141/103782972-6e120f00-5038-11eb-8b72-5834ebbac71d.gif)

**Comment by Swampen** [comment]
Is the configuration still the same?
If so, have you tried to remove the icon option?

Regarding the issue external link, it should be easy enough to add. You want it to open a new tab with the external link?

**Comment by Mariusthvdb** [comment]
> Is the configuration still the same?
this is what I am using now (the navigation_path isn't used by the card, but I left it as a promise to myself to keep trying...)
```
type: custom:air-visual-card
air_pollution_level: sensor.u_s_air_pollution_level
air_quality_index: sensor.u_s_air_quality_index
main_pollutant: sensor.u_s_main_pollutant
temp: sensor.plugwise_outdoor_temperature
country: NL
city: Woensdrecht
icons: /local/weather/aqi_icons/
icon_sensor: sensor.weather_icon
hide_title: false
hide_face: false
navigation_path: https://www.airvisual.com/netherlands/north-brabant/huijbergen/huijbergen-vennekenstraat
```

> If so, have you tried to remove the icon option?

which is that?

> Regarding the issue external link, it should be easy enough to add. You want it to open a new tab with the external link?

YES!!! please. sorry for shouting but this seems so logical (and easy) and I have never been able to, so getting somewhat excited here....

**Comment by Swampen** [comment]
Try to remove the `icons: /local/weather/aqi_icons/` option from the configuration and see if it gets any better

**Comment by Mariusthvdb** [comment]
Yes! it seems to have stopped immediately (knocking on wood now, because I have thought that before)

How can this be? Isn't this necessary any more?

**Comment by Swampen** [comment]
Correct. This option is optional as described in the documentation: "The local directory where the .svg files are located. For example, 'icons: "/hacsfiles/air-visual-card"' is appropriate if this plugin is installed using HACS. If left blank, icons will be loaded from Jsdeliver CDN."

**Comment by Mariusthvdb** [comment]
Ah, yes, but I downloaded them so not tom have the instance need external access. Trying to be as independent as possible from the outside world... cant we make this more robust when reading the icons locally?

**Comment by Swampen** [comment]
It might be some issues with the card refreshing quite often. 
I will look into what's causing it

**Comment by Swampen** [comment]
The cause of the issue is Home Assistant itself trying to refresh the card frequently. This means that it has to load the picture every time it refreshes. This is the natural behavior.

@dnguyen800  If you have any plans of moving the card from pure JS to use a package manager like node, you can use the [custom-card-helpers](https://www.npmjs.com/package/custom-card-helpers) module with the `hasConfigOrEntityChanged` helper method.

In the meantime I have created a helper method to check if there is any changes in any of the states before it refreshes the card (PR incoming)

**Comment by dnguyen800** [comment]
Thank you @Swampen for looking into this. I'm not familiar with package managers so I wouldn't know how to start using Node. I would love to continue practicing coding but I don't have the time anymore. 

If you're interested in continuing development of this card, you can fork it and I can ask to replace my repo with yours on HACS. Or you can write your own card from scratch, which I'm sure would be much cleaner version than mine. Either way, I'm happy to continue testing and approving your PRs.

I'll study your PR to see if I can apply the same helper method to my Quote of the Day card :)
