### ISSUE TITLE
AQI 50 is displayed as Moderate, Should be Good ??

### ISSUE THREAD

**Issue by MarsWarrior** [dnguyen800/air-visual-card#3]
On the AirVisual site, 50 is displayed as "Good":
![image](https://user-images.githubusercontent.com/1220775/62459141-e8bd6780-b77e-11e9-9121-72763868e400.png)

The card in Hass shows "Moderate", although I sometimes see "Good" with a yellow background:
![image](https://user-images.githubusercontent.com/1220775/62459177-fecb2800-b77e-11e9-9764-d8ab6ff522ba.png)

**Comment by dnguyen800** [comment]
Good catch! The error is in my code here:

```
          case (aqiSensor.value < 50):
```

It should be:

```
          case (aqiSensor.value <= 50):
```

I will be making updates to the card later this week, but if you would like to make the change now, you can edit the .js file directly with this change.

**Comment by dnguyen800** [comment]
fixed in latest release, thanks.
