### ISSUE TITLE
Make it compatible with WAQI.

### ISSUE THREAD

**Issue by Ndrinta** [dnguyen800/air-visual-card#35]
Given the recent issues with the AirVisual API ([#42776](https://github.com/home-assistant/core/issues/42776#event-3970974591)), I'd be nice to have a backup when stuff like this happen. 
[WAQI](https://www.home-assistant.io/integrations/waqi/) looks like the only alternative for home assistant right now.

Is this feasible?

**Comment by dnguyen800** [comment]
thanks for letting me know about WAQI. I'll see what sensors are available from this integration.

**Comment by Ndrinta** [comment]
#https://github.com/home-assistant/core/issues/42776#issue-734897729

**Comment by Ndrinta** [comment]
Super-quick fix if you don't want to wait.
These sensors make WAQI compatible with AirVisual Card.

# === Sensors
sensor:

    # World Air Quality Index (WAQI) - [https://www.home-assistant.io/integrations/waqi/]
  - platform: waqi
    token: !secret waqi_api_key
    locations:
      - Coventry # YOUR_LOCATION
    stations: 
      - "Coventry Allesley, United Kingdom" # STATION_OF_INTEREST_1
      - "Coventry Memorial Park, United Kingdom" # STATION_OF_INTEREST_2

    # Pollution Level (from WAQI)
  - platform: template
    sensors:
      waqi_air_pollution_level:
        friendly_name: WAQI Pollution Level
        value_template: >-
          {% set level = ((states('sensor.waqi_coventry_allesley_united_kingdom')|int + states('sensor.waqi_coventry_memorial_park_united_kingdom')|int) / 2 )|int %}
          {% if level <= 50 %}
            Good
          {% elif level <= 100 %}
            Moderate
          {% elif level <= 200 %}
            Unhealty
          {% elif level <= 300 %}
            Very Unhealty
          {% else %}
            Hazardous
          {% endif %}
        icon_template: >-
          {% set level = ((states('sensor.waqi_coventry_allesley_united_kingdom')|int + states('sensor.waqi_coventry_memorial_park_united_kingdom')|int) / 2 )|int %}
          {% if level <= 50 %}
            mdi:emoticon-excited
          {% elif level <= 100 %}
            mdi:emoticon-happy
          {% elif level <= 150 %}
            mdi:emoticon-neutral
          {% elif level <= 200 %}
            mdi:emoticon-sad
          {% elif level <= 300 %}
            mdi:emoticon-dead
          {% else %}
            mdi:biohazard
          {% endif %}
#        attribute_templates:
#          latitude:  >-
#            {{ state_attr('sensor.u_s_air_pollution_level','latitude') }}
#          longitude:  >-
#            {{ state_attr('sensor.u_s_air_pollution_level','longitude') }}

    # Quality Index (from WAQI)
  - platform: template
    sensors:
      waqi_air_quality_index:
        friendly_name: WAQI Quality Index
        value_template: >-
          {{ ((states('sensor.waqi_coventry_allesley_united_kingdom')|int + states('sensor.waqi_coventry_memorial_park_united_kingdom')|int) / 2 )|int}}
        unit_of_measurement: 'AQI'
          
    # Main Pollutant (from WAQI)
  - platform: template
    sensors:
      waqi_main_pollutant:
        friendly_name: WAQI Main Pollutant
        value_template: >-
          {% set main_pollutant = state_attr('sensor.waqi_coventry_allesley_united_kingdom','dominentpol') %}
          {% if main_pollutant == "pm25" %}
            PM2.5
          {% elif main_pollutant == "pm10" %}
            PM10
          {% elif main_pollutant == "o3" %}
            Ozone
          {% elif main_pollutant == "no2" %}
            Nitrogen Dioxide
          {% elif main_pollutant == "so2" %}
            Sulfur Dioxide
          {% else %}
            Unknown
          {% endif %}
        attribute_templates:
          pollutant_unit: >-
            {% set main_pollutant = state_attr('sensor.waqi_coventry_allesley_united_kingdom','dominentpol') %}
            {% if main_pollutant == "pm25" %}
              µg/m³
            {% elif main_pollutant == "pm10" %}
              µg/m³
            {% elif main_pollutant == "o3" %}
              ppb
            {% elif main_pollutant == "no2" %}
              ppb
            {% elif main_pollutant == "so2" %}
              ppb
            {% else %}
              Unknown
            {% endif %}

    # Outside Temperature (from WAQI)
  - platform: template
    sensors:
      waqi_temperature:
        friendly_name: WAQI Temperature
        unit_of_measurement: '°C'
        value_template: >-
          {{ state_attr('sensor.waqi_coventry_allesley_united_kingdom','temperature') }}
        device_class: temperature
This is a bodge, there are shortcuts and imprecisions. I did my best, I'm sure there are imprecisions and I'm open to suggestions!
I left my Location and Stations of interest in so for you to quickly try the config with a working one, change it accordingly to your location.
I decided to select those 2 stations because if you don't the integration populate a 3rd sensor (in my specific case) which is not of interest (somewhere in US I think), and I thought it was a waste of resources.
I chose to make the average of the 2 sensors (for a try) but to take in consideration only the closest station for the main pollutant.

In the declaration of sensor.waqi_air_pollution_level latitude and longitude attributes are commented out, this because I found out are not strictly necessary for the functionality of AirVisual Card.

**Comment by dnguyen800** [comment]
Thanks. I started implementing it but ran into some issues. I'm pretty slow so it's good you wrote a template sensor instead. Thanks for figuring out the values for main pollutant, I will add that to the code.

**Comment by Ndrinta** [comment]
I'll leave this with you. Shout if you need any help, closing this now. Cheers

**Comment by dnguyen800** [comment]
Hey @Ndrinta , I'm almost done adding WAQI support, but wanted your help on calculating this value (see red circle)

![image](https://user-images.githubusercontent.com/25126347/99131573-61d57c80-25c8-11eb-87e3-22ebc00220e7.png)

Do you know how this value is calculated? Is it possible to calculate with the data from the WAQI sensors?

**Comment by dnguyen800** [comment]
I've added in WAQI support, but I'm not going to publish a new release due to insufficient testing. It technically works, and if Airvisual has problems again, I'll probably pick this up again.

You can put the .js file in your /www/community/air-visual-card directory
https://github.com/dnguyen800/air-visual-card/blob/master/dist/air-visual-card.js

**Comment by Ndrinta** [comment]
Amazing, thanks!
I'll give it a go early next week and let you know if anything odd.

> Do you know how this value is calculated? Is it possible to calculate with the data from the WAQI sensors?

As far as I know, the AQI is "calculated" in this way:
`Raw concentration (pollutant) = Reference value (pollutant) * AQI }(pollutant) / 50`
The main pollutant raw value isn't provided by the AirVisual integration but it's available with the WAQI integration instead. And not only the main one, but all (super cool). (Note: The value for 'Sulfur' is missing from WAQI)

![image](https://user-images.githubusercontent.com/4704172/99186583-30d08580-2749-11eb-9f71-6be9e63e3394.png)

Also, if I can say, the way in which IQAir derives the Air Quality Index (AQI) is a bit of a mystery:

> The index formula usually considers up to 6 main pollutants (PM2.5, PM10, carbon monoxide, sulfur dioxide, nitrogen dioxide and ground level ozone), and calculates the respective health risk (or AQI number) for each one at any given time. The overall AQI number at a given moment is dictated by the "riskiest" pollutant, with the highest AQI number.

While WAQI is pretty simple and open (US EPA standard).
Sweet article you might be interdireste in (https://aqicn.org/faq/2015-07-16/air-quality-scale-in-quebec-and-montreal/faq/2015-03-20/a-comparison-of-worldwide-air-quality-scales-part-1/faq/2015-03-20/a-comparison-of-worldwide-air-quality-scales-part-1/), check the bottom of the page _(Note: This article is part of a series on Worlwide Air Quality scales.)_, more in there. Furthermore, IQAir use data not only from certified stations but also from their (indoor) AirVisual Pro sensors they sell all around the world. I'm not sure how that impacts the data but I would't trust data coming from end users (never ever, ahah).

**Comment by jokerigno** [comment]
Hi all,

I've setup a air visual card using WAQI from a year or so.

I worked great but starting from few days values are always shown in english even if my template sensor use my native language:

CARD:

```
air_pollution_level: sensor.aqicn
air_quality_index: sensor.waqi_rebaudengo_torino_piemonte_italy 
main_pollutant: sensor.dominentpol
hide_face: true
type: 'custom:air-visual-card'
```

SENSOR

```
  - platform: waqi
    token: xxxxxxxxxxxxxxxxxxxxxxxxx
    locations:
      - Rebaudengo, Torino, Piemonte
        
  - platform: template
    sensors:  
      aqicn:
        friendly_name: "Qualità dell'aria a Torino" 
        value_template: >-
          {% if states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 50 %}
          Buona
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 100%}
          Moderata
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 150%}
          Insalubre per alcuni
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 200 %}
          Insalubre
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 300 %}
          Molto insalubre
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int >= 300 %}
          Pericolosa
          {% endif %}
        icon_template: >-
          {% if states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 50 %}
            mdi:emoticon-excited
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 100%}
            mdi:emoticon-happy
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 150%}
            mdi:emoticon-neutral
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 200 %}
            mdi:emoticon-sad
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int <= 300 %}
            mdi:emoticon-dead
          {% elif states('sensor.waqi_rebaudengo_torino_piemonte_italy')|int >= 300 %}
            mdi:biohazard
          {% endif %}


  - platform: template
    sensors:
      dominentpol:
        friendly_name: Inquinante principale
        value_template: >-
          {% set main_pollutant = state_attr('sensor.waqi_rebaudengo_torino_piemonte_italy','dominentpol') %}
          {% if main_pollutant == "pm25" %}
            PM2.5
          {% elif main_pollutant == "pm10" %}
            PM10
          {% elif main_pollutant == "o3" %}
            Ozono
          {% elif main_pollutant == "no2" %}
            Diossido di azoto
          {% elif main_pollutant == "so2" %}
            Anidride solforosa
          {% else %}
            Sconosciuto
          {% endif %}
        attribute_templates:
          pollutant_unit: >-
            {% set main_pollutant = state_attr('sensor.waqi_rebaudengo_torino_piemonte_italy','dominentpol') %}
            {% if main_pollutant == "pm25" %}
              µg/m³
            {% elif main_pollutant == "pm10" %}
              µg/m³
            {% elif main_pollutant == "o3" %}
              ppb
            {% elif main_pollutant == "no2" %}
              ppb
            {% elif main_pollutant == "so2" %}
              ppb
            {% else %}
              Sconosciuto
            {% endif %}
```

Has something changed?

**Comment by ranrinc** [comment]
Need help on AirVisual since I try to follow everyone's guide here.

However, it seems to not be able to show its value_template

Any help?

The View which missing PM2.5 value and Status
<img width="501" alt="Screen Shot 2022-06-22 at 9 28 28 AM" src="https://user-images.githubusercontent.com/15801696/174931825-9f06682a-1bcc-48e9-bb0b-e82e9a575f53.png">

The value from both sensor is working fine
<img width="892" alt="Screen Shot 2022-06-22 at 9 29 12 AM" src="https://user-images.githubusercontent.com/15801696/174931906-e76d7404-e64c-45cf-a64f-8ce9dd9453af.png">


MySetup
```
- type: custom:air-visual-card
  air_pollution_level: sensor.waqi_pollution_level_jakarta
  air_quality_index: sensor.waqi_jakarta_indonesia
  main_pollutant: sensor.waqi_main_pollutant_jakarta
  weather: weather.home
  hide_weather: 1
  hide_title: 1
  hide_face: 0

- platform: template
  sensors:  
    waqi_pollution_level_jakarta:
      friendly_name: WAQI Pollution Level Jakarta
      value_template: >-
        {% if states('sensor.waqi_jakarta_indonesia')|int <= 50 %}
          good
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 100%}
          moderate
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 150%}
          unhealthy_sensitive
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 200 %}
          unhealthy
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 300 %}
          very_unhealthy
        {% elif states('sensor.waqi_jakarta_indonesia')|int >= 300 %}
          hazardous
        {% endif %}
      icon_template: >-
        {% if states('sensor.waqi_jakarta_indonesia')|int <= 50 %}
          mdi:emoticon-excited
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 100%}
          mdi:emoticon-happy
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 150%}
          mdi:emoticon-neutral
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 200 %}
          mdi:emoticon-sad
        {% elif states('sensor.waqi_jakarta_indonesia')|int <= 300 %}
          mdi:emoticon-dead
        {% elif states('sensor.waqi_jakarta_indonesia')|int >= 300 %}
          mdi:biohazard
        {% endif %}

- platform: template
  sensors:
    waqi_main_pollutant_jakarta:
      friendly_name: WAQI Main Pollutant Jakarta
      value_template: >-
        {% set main_pollutant = state_attr('sensor.waqi_jakarta_indonesia','dominentpol') %}
        {% if main_pollutant == "pm25" %}
          p2
        {% elif main_pollutant == "pm10" %}
          p1
        {% elif main_pollutant == "co" %}
          co
        {% elif main_pollutant == "o3" %}
          o3
        {% elif main_pollutant == "no2" %}
          n2
        {% elif main_pollutant == "so2" %}
          s2
        {% else %}
          Unknown
        {% endif %}
      attribute_templates:
        pollutant_unit: >-
          {% set main_pollutant = state_attr('sensor.waqi_jakarta_indonesia','dominentpol') %}
          {% if main_pollutant == "pm25" %}
            µg/m³
          {% elif main_pollutant == "pm10" %}
            µg/m³
          {% elif main_pollutant == "co" %}
            ppm
          {% elif main_pollutant == "o3" %}
            ppb
          {% elif main_pollutant == "no2" %}
            ppb
          {% elif main_pollutant == "so2" %}
            ppb
          {% else %}
            Unknown
          {% endif %}
```

**Comment by jukkaphat** [comment]
> Need help on AirVisual since I try to follow everyone's guide here.
> 
> However, it seems to not be able to show its value_template
> 
> Any help?
> 
> The View which missing PM2.5 value and Status <img alt="Screen Shot 2022-06-22 at 9 28 28 AM" width="501" src="https://user-images.githubusercontent.com/15801696/174931825-9f06682a-1bcc-48e9-bb0b-e82e9a575f53.png">
> 
> The value from both sensor is working fine <img alt="Screen Shot 2022-06-22 at 9 29 12 AM" width="892" src="https://user-images.githubusercontent.com/15801696/174931906-e76d7404-e64c-45cf-a64f-8ce9dd9453af.png">
> 
> MySetup
> 
> ```
> - type: custom:air-visual-card
>   air_pollution_level: sensor.waqi_pollution_level_jakarta
>   air_quality_index: sensor.waqi_jakarta_indonesia
>   main_pollutant: sensor.waqi_main_pollutant_jakarta
>   weather: weather.home
>   hide_weather: 1
>   hide_title: 1
>   hide_face: 0
> 
> - platform: template
>   sensors:  
>     waqi_pollution_level_jakarta:
>       friendly_name: WAQI Pollution Level Jakarta
>       value_template: >-
>         {% if states('sensor.waqi_jakarta_indonesia')|int <= 50 %}
>           good
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 100%}
>           moderate
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 150%}
>           unhealthy_sensitive
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 200 %}
>           unhealthy
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 300 %}
>           very_unhealthy
>         {% elif states('sensor.waqi_jakarta_indonesia')|int >= 300 %}
>           hazardous
>         {% endif %}
>       icon_template: >-
>         {% if states('sensor.waqi_jakarta_indonesia')|int <= 50 %}
>           mdi:emoticon-excited
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 100%}
>           mdi:emoticon-happy
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 150%}
>           mdi:emoticon-neutral
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 200 %}
>           mdi:emoticon-sad
>         {% elif states('sensor.waqi_jakarta_indonesia')|int <= 300 %}
>           mdi:emoticon-dead
>         {% elif states('sensor.waqi_jakarta_indonesia')|int >= 300 %}
>           mdi:biohazard
>         {% endif %}
> 
> - platform: template
>   sensors:
>     waqi_main_pollutant_jakarta:
>       friendly_name: WAQI Main Pollutant Jakarta
>       value_template: >-
>         {% set main_pollutant = state_attr('sensor.waqi_jakarta_indonesia','dominentpol') %}
>         {% if main_pollutant == "pm25" %}
>           p2
>         {% elif main_pollutant == "pm10" %}
>           p1
>         {% elif main_pollutant == "co" %}
>           co
>         {% elif main_pollutant == "o3" %}
>           o3
>         {% elif main_pollutant == "no2" %}
>           n2
>         {% elif main_pollutant == "so2" %}
>           s2
>         {% else %}
>           Unknown
>         {% endif %}
>       attribute_templates:
>         pollutant_unit: >-
>           {% set main_pollutant = state_attr('sensor.waqi_jakarta_indonesia','dominentpol') %}
>           {% if main_pollutant == "pm25" %}
>             µg/m³
>           {% elif main_pollutant == "pm10" %}
>             µg/m³
>           {% elif main_pollutant == "co" %}
>             ppm
>           {% elif main_pollutant == "o3" %}
>             ppb
>           {% elif main_pollutant == "no2" %}
>             ppb
>           {% elif main_pollutant == "so2" %}
>             ppb
>           {% else %}
>             Unknown
>           {% endif %}
> ```

I having the same problem here.

**Comment by ngseer** [comment]
Hi guys. I've made [a little tweak](https://github.com/ngseer/air-visual-card/blob/master/dist/air-visual-card.js) to show main pollutant value when using WAQI sensor. Can't tell if I did it 100% right (this is my first time tinkering with Lovelace cards tbh) but you all are very welcome to take a look at it.

![image](https://user-images.githubusercontent.com/4006975/178117252-d82c02d4-586c-49aa-b00f-eed54a3f9f97.png)

**Comment by fcastilloec** [comment]
I'm using only WAQI and I have the same problem. Only AQI is shown and nothing else, no text, no pollutant.

**Comment by jurgenweber** [comment]
@ngseer even using your repo; I still get: 

![image](https://user-images.githubusercontent.com/3013734/195582350-1de4223d-5c71-4f82-9638-4a49d72ce246.png)

**Comment by c0bra99** [comment]
AirVisual suddenly stopped working for my city for some reason (returns city_not_found) so I switched to the WAQI integration. I was pleasantly surprised that this air-visual-card worked just fine with no extra sensors or modifications required, I just put the same waqi sensor for all 3 air quality entities.

![image](https://user-images.githubusercontent.com/148933/196181330-51533655-524f-4c92-b4e3-67e8a090d042.png)
