### ISSUE TITLE
Crazy, impossible to find in HACS

### ISSUE THREAD

**Issue by nardev** [dnguyen800/air-visual-card#43]
Crazy situation,

it's impossible to find it in HACS and at the same time, when i try to add it manually in HACS it says "Repository 'dnguyen800/air-visual-card' exists in the store."

Also, it's impossible to add it manually.

I tried each and every method, it simply doesn't work.

Lovelace doesn't recognize it as custom card.

**Comment by dnguyen800** [comment]
I just removed and re-added the card through HACS right now, so I think it is still there. HACS search can be confusing, so make sure you do the following:

If the card is already installed in HACS, then you can use the search field to find it. If it's not installed, then you click the "+ Explore & Add Repositories" button and search for the name.

![image](https://user-images.githubusercontent.com/25126347/112759714-1cc74b00-8fa9-11eb-9bef-a1289fd8956a.png)

**Comment by Laikol** [comment]
Hello!

I thought I had the same problem until I realized that I was clicking on _Explore and add Repository_ button from the _Integrations_ section and not the _Frontend_... The button is exactly the same on both section but do not give the same content.
Anyway, maybe that is also your issue @nardev
