### ISSUE TITLE
"US AQI" displayed on the card even when using Chinese measurements

### ISSUE THREAD

**Issue by aleksandar-todorovic** [dnguyen800/air-visual-card#6]
Here are two cards next to each other:

![Screenshot from 2019-10-12 01-03-41@2x](https://user-images.githubusercontent.com/4890548/66689703-493fb800-ec8c-11e9-8166-8b6e53bc935c.png)

The difference between them is that the left one uses the US scale, while the right one uses the Chinese scale. Despite that, they both have "US AQI" displayed below the value.

**Comment by dnguyen800** [comment]
Yes, those are hard-coded in the card right now. I'll likely add a configuration option called `country: ` where you can replace `US` with another country's name.

**Comment by dnguyen800** [comment]
Fixed in latest release. Use the config option `country: ` and type China or any country name.
