### ISSUE TITLE
no value for µg/m³

### ISSUE THREAD

**Issue by Mariusthvdb** [dnguyen800/air-visual-card#7]
when checking the website for the station I use, a value is displayed before the unit µg/m³.
![Schermafbeelding 2019-10-17 om 09 25 16](https://user-images.githubusercontent.com/33354141/66987108-675c4c80-f0c0-11e9-9f76-79752c35c9c1.png)

which seems the sole purpose for this unit.

on the card no such value is displayed:

![Schermafbeelding 2019-10-17 om 09 28 33](https://user-images.githubusercontent.com/33354141/66987177-865ade80-f0c0-11e9-84f0-fc1a8bcf394e.png)

I don't think it is configured in the card at all?

Tried to find it in the sensors, I must admit I cant find the value for this unit anywhere..... Would this be a bug in the sensors/integration?

Ill post this on [the community](https://community.home-assistant.io/t/no-state-value-for-air-visual-integration-main-sensor/142908) also. thanks!

**Comment by dnguyen800** [comment]
I think that data is the Key pollutant concentration values, which is not available in the Airvisual's community API. You'll have to pay money to get that data. I can't do anything on my end.

**Comment by Mariusthvdb** [comment]
Yes, thx
