### ISSUE TITLE
add external Air-visual navigate to click on City

### ISSUE THREAD

**Issue by Mariusthvdb** [dnguyen800/air-visual-card#8]
please consider adding the option to navigate to an external web-address, suggest the air_visual address of the station.
I've added this to the card:

```
      card.querySelector('#city').addEventListener('click', event => {
        fireEvent(this, "navigate", { entityId: webAddress.config });
      });
```

and

```
      const webAddress = {name: 'webAddress', config: config.web_address || '';
```

not sure what the action name for 'navigate' should be though.

in the card config, I've added:

```
web_address: https://www.airvisual.com/netherlands/north-brabant/huijbergen/huijbergen-vennekenstraat
```
obviously this doesn't work, since the action is incorrect. Also the click on city doesn't yet work for any more-info, apparently this code is not yet as it should be....sorry, hope you get the idea.

please have a look? thanks!

**Comment by Mariusthvdb** [comment]
have you given this any thought yet? would really be very nice to add.

I've put forward all info I could think of, but can't get the click to result in a navigate... should we use has-navigate maybe? And how to have it point to the desired web-address?
Hope you could help and find out please.

**Comment by dnguyen800** [comment]
Sorry, don't have any time to look at this until the holidays. I wouldn't know how to implement this Ina good way except by applying <a href> html tag to the item. Even with that, can't guarantee that solution will work with the mobile apps so it's not really a priority for me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mariusthvdb** [comment]
ok cool, no hurry ;-)

just to let you know I've tried this also, (have the city and temp show a more-info), but that doesn't seem to work either. It does activate something, because it brings me to my homepage.... 

```
      let faceHTML = ``;

      let card_content = `
        <div class="grid-container" style="background-color: ${AQIbgColor[getAQI()]};">
        `;
      if (!hideTitle) {
        card_content += `
        <div class="city" id="city">${city}</div>
        <div class="temp" id="temp"><ha-icon icon="${hass.states[iconSensor].state}"></ha-icon> ${tempValue}</div>
        `;
      }

      card_content += `
          <div class="face" id="face" style="background-color: ${AQIfaceColor[getAQI()]};">
            <img src="${iconDirectory}/ic-face-${getAQI()}.svg"></img>
          </div>
          <div class="aqiSensor" id="aqiSensor" style="background-color: ${AQIbgColor[getAQI()]}; color: ${AQIfontColor[getAQI()]}">
            <div style="font-size:3em;">${aqiSensor.value}</div>
            ${country} ${unitOfMeasurement}
          </div>
          <div class="aplSensor" id="aplSensor" style="background-color: ${AQIbgColor[getAQI()]}; color: ${AQIfontColor[getAQI()]}">
            ${aplSensor.value}
            <br>
            <br>
            <div class="mainPollutantSensor" id="mainPollutantSensor">
              ${mainPollutantSensor.value} | ${pollutantUnit}
            </div>
          </div>
        </div> 
      `;

      root.lastChild.hass = hass;
      root.getElementById('content').innerHTML = card_content;

      // hard-coded version of click event
      card.querySelector('#city').addEventListener('click', event => {
        fireEvent(this, "hass-more-info", {entityId: aqiSensor.config });
      });
      card.querySelector('#temp').addEventListener('click', event => {
        fireEvent(this, "hass-more-info", { entityId: aplSensor.config });
      });
      card.querySelector('#face').addEventListener('click', event => {   // when selecting HTML id, do not use dash '-'  
        fireEvent(this, "hass-more-info", { entityId: aplSensor.config });
      });     
      card.querySelector('#aqiSensor').addEventListener('click', event => {   // when selecting HTML id, do not use dash '-'  
        fireEvent(this, "hass-more-info", { entityId: aqiSensor.config });
      });
      card.querySelector('#aplSensor').addEventListener('click', event => {   // when selecting HTML id, do not use dash '-'  
       fireEvent(this, "hass-more-info", { entityId: mainPollutantSensor.config });
      });
      card.querySelector('#mainPollutantSensor').addEventListener('click', event => {   // when selecting HTML id, do not use dash '-'  
        fireEvent(this, "hass-more-info", { entityId: mainPollutantSensor.config });
      });
```

anyways, would be really cool if the navigate would be allowed somehow. Especially since we can do that now natively in HA for entitities:

https://www.home-assistant.io/lovelace/entities/#url_path

**Comment by Mariusthvdb** [comment]
HI!
are you still developing this card, so I could hope to see this feature some day?
If not, I'd be happy to try myself, if you could only guide to applying the <a href> html tag and where to put it in the code.

Or, simply by allowing the tap/hold action of the core Ha code maybe?
anyways, thanks for considering.

**Comment by dnguyen800** [comment]
I never figured out how to do this, so can't help you, sorry.

**Comment by Swampen** [comment]
@Mariusthvdb If you want to add this to your own card, you can do it by adding this:
```javascript
card.querySelector('#city').addEventListener('click', event => {
    window.open(webAddress, '_blank');
});
```

But I personally would not want to add this feature as it navigates to websites outside the HA environment.

**Comment by Mariusthvdb** [comment]
thanks, I will try!
Can we modify this to navigate to another view too? (have a view with all climate settings I would like to hold-click to...)

I understand what you say on navigating outside th HA environment. Thats why it might be even better if the card would implement the [core configuration variables ](https://www.home-assistant.io/lovelace/actions/#configuration-variables) for `navigation_path` And `url_path`

**Comment by Mariusthvdb** [comment]
to keep thing tidy, allow this separate post.

Ive added the constant:

```
const urlPath = {name: 'urlPath', config: config.url_path || '' };
```
and in the card config:
```
url_path: https://www.airvisual.com/netherlands/north-brabant/huijbergen/huijbergen-vennekenstraat
```

in the final card_content, I've added:
```
      card.querySelector('#city').addEventListener('click', event => {
        window.open(urlPath, '_blank');
      });
```

something is openend on the click, but it leads to `https://mydomain.duckdns.org:port/lovelace/[object%20Object]`

so, though progress, Im not there yet....

please have another look?

**Comment by Swampen** [comment]
I don't think there is any easy way to implement the existing features of some lovelace cards. I might be adding it if I decide to rewrite the card.

To fix your navigation, just use
```javascript
// Change to this
const urlPath = config.url_path || '' ;
//or this
card.querySelector('#city').addEventListener('click', event => {
  window.open(urlPath.config, '_blank');
});
```

**Comment by Mariusthvdb** [comment]
Bingo!
using the 2nd option.

found out that www.airvisual.com is now redirected to www.iqair.com. And, they now have a station in my municipality ;-)
so, using

```
type: custom:air-visual-card
air_pollution_level: sensor.u_s_air_pollution_level
air_quality_index: sensor.u_s_air_quality_index
main_pollutant: sensor.u_s_main_pollutant
temp: sensor.plugwise_outdoor_temperature
country: NL
city: Roosendaal
icons: /local/weather/aqi_icons/
icon_sensor: sensor.weather_icon
hide_title: false
hide_face: false
url_path: https://www.iqair.com/netherlands/north-brabant/roosendaal
```

results in:

<img width="497" alt="Schermafbeelding 2021-01-07 om 10 54 43" src="https://user-images.githubusercontent.com/33354141/103878481-c566bc80-50d6-11eb-8d03-dd1c56c558c2.png">

clicking 'Roosendaal' opens:

<img width="1836" alt="Schermafbeelding 2021-01-07 om 10 55 20" src="https://user-images.githubusercontent.com/33354141/103878543-dca5aa00-50d6-11eb-9bb0-a4b5a6583c05.png">

so cool, many thanks!

**Comment by Mariusthvdb** [comment]
re-comment on this.
Unfortunately, after updastin g to the latest version (18) today and adding my personal edit from above discussion:
```
      // hard-coded version of click event
      card.querySelector('#city').addEventListener('click', event => {
        window.open(urlPath.config, '_blank');
      });
```

the navigate doesn't work anymore. I must admit I haven't tested that in the previous HA version (now using the September  beta 2021.9.0b6), so maybe it was already dysfunctional before.

would you please have a look what could be causing this? Really liked the navigate to the source material on a click.

And yes, before you ask, I did also add the identifier on city (and temp):
```
      if (!hideTitle) {
        card_content += `
        <div class="city" id="city" style="background-color: ${AQIbgColor[getAQI()]};">${city}</div>
        <div class="temp" id="temp" style="background-color: ${AQIbgColor[getAQI()]};"><ha-icon icon="${weatherIcons[currentCondition]}"></ha-icon>   ${tempValue}</div>
        `;
      }
```
