### ISSUE TITLE
No city selected, header in full high

### ISSUE THREAD

**Issue by GOSSIP-Blockchain** [dnguyen800/air-visual-card#9]
I don't want to see the city and weather. Please remove the header line when no city is selected.

![image](https://user-images.githubusercontent.com/39032310/67619817-941b0d00-f800-11e9-940b-5da16cd0c7fa.png)

![image](https://user-images.githubusercontent.com/39032310/67619854-d17f9a80-f800-11e9-89d4-d7832963a173.png)

**Comment by dnguyen800** [comment]
update to the latest version of the card and use the option `hide_title: true`
